config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  get 'login', to: 'sessions#new_login'
  post 'login', to: 'sessions#create_login'
  get 'register', to: 'sessions#new_register'
  post 'register', to: 'sessions#create_register'
  delete 'logout', to: 'sessions#destroy'
  resources :posts do
    resources :comments, only: %i[create edit update destroy]
    resources :reactions, only: %i[create update destroy]
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :thumbnail, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  before_destroy :cleanup_thumbnail
  # after_update :cleanup_thumbnail, if: :saved_change_to_thumbnail?

  private

  def cleanup_thumbnail
    thumbnail.purge_later
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authorize_admin, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  def index
    @pagy, @posts = pagy(Post.all)
  end

  # GET /posts/1
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:title, :body, :thumbnail)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: "needs-validation", novalidate: true) do |form| %>
  <div class="form-group mb-2">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control', placeholder: "Enter title" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control', rows: 3, placeholder: "Enter body text" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :thumbnail, class: 'form-label' %>
    <%= form.file_field :thumbnail, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<div class="col">
  <div class="card shadow-sm">
    <%= cl_image_tag post.thumbnail.key, :crop => "thumb", height: 225, class: "card-img-top" %>
    <div class="card-body">
      <p class="card-text"><%= post.title %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", post, class: "btn btn-sm btn-outline-secondary" %>
          <% if current_user&.is_admin %>
            <%= link_to "Edit", edit_post_path(post), class: "btn btn-sm btn-outline-secondary" %>
          <% end %>
        </div>
        <small class="text-body-secondary">9 mins</small>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center">New Post</h1>
        </div>
        <div class="card-body">
          <%= render 'form', post: @post %>
          <%= link_to 'Back', posts_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">My blog</h1>
      <p class="lead text-body-secondary">
        Here I will post my guides, thoughts and other information worth sharing.<br />
        Make sure you are logged in if you want to comment or react.
      </p>
      <% if current_user == nil %>
        <p>
          <%= link_to 'Register', register_path, class: "btn btn-primary my-2" %>
          <%= link_to 'Login', login_path, class: "btn btn-secondary my-2" %>
        </p>
      <% else %>
        <p>
          <%= button_to 'Logout', logout_path, method: :delete, form: { data: { turbo: true } },
                        class: "btn btn-primary my-2" %>
          <% if current_user.is_admin %>
            <%= link_to 'Create new post', new_post_path, class: "btn btn-secondary my-2" %>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>
</section>

<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <%#= turbo_frame_tag "posts" do %>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-3">
        <%= render @posts %>
      </div>
      <% if @pagy.pages > 1 %>
        <div class="d-flex justify-content-center">
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
        <div class="text-center text-muted">
          <%== pagy_info(@pagy) %>
        </div>
      <% end %>
    <%# end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center">New Post</h1>
        </div>
        <div class="card-body">
          <%= render 'form', post: @post %>
          <%= link_to 'Back', posts_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card p-3">
        <div class="card-header">
          <h1><%= @post.title %></h1>
        </div>
        <% if @post.thumbnail.attached? %>
          <%= cl_image_tag @post.thumbnail.key, :crop => "fill", class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <p class="card-text"><%= markdown(@post.body) %></p>
        </div>
        <hr />
        <%= render "reactions/reactions", post: @post %>
        <h3>Comments:</h3>
        <%= turbo_frame_tag "comments" do %>
          <div id="comments">
            <%= render @post.comments, post_id: @post.id %>
          </div>
        <% end %>
        <% if current_user.present? %>
          <div class="mt-3">
            <%= render "comments/new", post: @post, comment: @comment, button_text: "Comment" %>
          </div>
        <% end %>
        <div class="card-footer text-muted mt-3">
          <%= link_to 'Back to Posts', posts_path, class: "btn btn-secondary" %>
          <% if current_user&.is_admin %>
            | <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info" %> |
            <%= link_to 'Delete', @post, data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            }, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>