config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  get 'login', to: 'sessions#new_login'
  post 'login', to: 'sessions#create_login'
  get 'register', to: 'sessions#new_register'
  post 'register', to: 'sessions#create_register'
  delete 'logout', to: 'sessions#destroy'
  resources :posts do
    resources :comments, only: %i[create edit update destroy]
    resources :reactions, only: %i[create update destroy]
  end
end

app/views/layouts/_active_link.html.erb
<%= link_to link, path, class: current_page?(path) ? "nav-link active" : "nav-link" %>

app/views/layouts/_flash.html.erb
<div class="flash-container">
  <% flash.each do |type, message| %>
    <div class="flash-message"
         data-controller="removals"
         data-action="animationend->removals#remove">
      <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissible fade show"
           role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md fixed-top bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Wiktor Szymulewicz", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= render "layouts/active_link", link: "Home", path: root_path %>
        </li>
        <li class="nav-item">
          <%= render "layouts/active_link", link: "Blog", path: posts_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link href="
      https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/journal/bootstrap.min.css"
          rel="stylesheet">
  </head>

  <body>
    <header data-bs-target="dark">
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <noscript>
        <% unless current_page?(home_index_path) || current_page?(root_path) %>
          <div class="noscript-warning">
            <div class="alert alert-danger" role="alert">
              You do not have JavaScript enabled. All of the site's functionality should work okay,
              except for deleting comments and reactions.
            </div>
          </div>
        <% end %>
      </noscript>
      <div id="flash">
        <%= render 'layouts/flash' %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>